apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: go-sicfoofu
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/go-sicfoofu:0f813d2848589f4f88391cc3ed2a6ea9a4d4f76f@sha256:05c248f627b93ee6f6cd82b5bffbf015dd6cdba21da918c55845ed543e564dfc
          name: container-image
